insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('6483482', 'Bins-Abbott', 'Industrial Machinery/Components', 'West End', 'Canada');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('4643676', 'Rolfson-Heller', 'Electric Utilities: Central', 'Villeurbanne', 'France');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('8458074', 'Murray, Hoeger and Wisozk', 'Marine Transportation', 'München', 'Germany');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('9766276', 'Dicki-Kuhic', 'Marine Transportation', 'Washington', 'United States');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('5198528', 'Fay-Lakin', 'n/a', 'Hénin-Beaumont', 'France');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('3269174', 'Schaefer-Jerde', 'n/a', 'Orléans', 'France');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('3101333', 'Robel, Gerhold and Weber', 'EDP Services', 'Rayside-Balfour', 'Canada');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('9670500', 'Rolfson Group', 'Specialty Insurers', 'Chattanooga', 'United States');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('0231629', 'Hyatt, Hyatt and Conroy', 'n/a', 'Birmingham', 'United States');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('8012217', 'Wilderman Inc', 'Food Distributors', 'Kugluktuk', 'Canada');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('8549372', 'Reynolds, Marquardt and Carter', 'Coal Mining', 'Mesa', 'United States');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('6383355', 'Brown and Sons', 'Real Estate Investment Trusts', 'Tours', 'France');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('0923146', 'Bogan-Hyatt', 'Telecommunications Equipment', 'Laurel', 'United States');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('3330110', 'Padberg Inc', 'Finance: Consumer Services', 'Arcueil', 'France');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('4647393', 'Pagac and Sons', 'Restaurants', 'Roubaix', 'France');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('8382907', 'Ebert-Crist', 'Oil & Gas Production', 'Royan', 'France');
insert into Clients (CompanyID, CompanyName, Industry, City, Country) values ('9812165', 'Rice-Witting', 'Business Services', 'Phoenix', 'United States');
